name: dbt_run_streamline_balances_history_temp
run-name: dbt_run_streamline_balances_history_temp

on:
  workflow_dispatch:
    branches:
      - "main"
  schedule:
    - cron: '26 */4 * * *'

concurrency:
  group: ${{ github.workflow }}

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/fsc-evm/.github/workflows/dbt_run_template.yml@main
    with:
      command_name: Run Balances History Temp Models
      command: |
        dbt run --vars '{"STREAMLINE_INVOKE_STREAMS":True, "BALANCES_SL_STATE_TRACER_HISTORY_SQL_LIMIT":100000, "BALANCES_SL_STATE_TRACER_HISTORY_PRODUCER_BATCH_SIZE":10000, "BALANCES_SL_STATE_TRACER_HISTORY_WORKER_BATCH_SIZE":500, "BALANCES_SL_STATE_TRACER_HISTORY_ASYNC_CONCURRENT_REQUESTS":50}' -m "fsc_evm,tag:streamline,tag:balances,tag:complete" "fsc_evm,tag:streamline,tag:balances,tag:history"
    secrets: inherit